# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel ddd
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master
      - name : deploy
        uses: lomi525/py-lambda-action@master
        with:
          package: lambda.zip
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          LAMBDA_FUNCTION_NAME: lambda_function.lambda_handler
          LAMBDA_LAYER_ARN: bs4_requrests_layer
